support timestamps
k2-fsa/sherpa-ncnn pull request #130
Opened 2023-02-28 12:51 UTC by xiangxyq

hi, our project need timestamps with sherpa-ncnn, current sherpa-ncnn has no timestamps output,  I have completed this. But also has some confusions:
1. [sherpa-ncnn-alsa.cc](https://github.com/k2-fsa/sherpa-ncnn/blob/master/sherpa-ncnn/csrc/sherpa-ncnn-alsa.cc) and [sherpa-ncnn-microphone.cc](https://github.com/k2-fsa/sherpa-ncnn/blob/master/sherpa-ncnn/csrc/sherpa-ncnn-microphone.cc) need to print timestamps result
2. https://github.com/xiangxyq/sherpa-ncnn/blob/cj-add-timestamps/sherpa-ncnn/csrc/recognizer.h#L38 timestamps use float instead int32, if use Convert like sherpa https://github.com/k2-fsa/sherpa/blob/4756d4ec10c61164eff356190740527993844df3/sherpa/cpp_api/online-stream.h#L17 , need extra struct
3. https://github.com/xiangxyq/sherpa-ncnn/blob/28b77f7f6f1820fb0149530b5ef5c933b7275fb2/sherpa-ncnn/csrc/greedy-search-decoder.cc#L43 here why  push blanck_id to token, how to handle timestamps?

Thanks!

2023-02-28 13:13 UTC, csukuangfj requested changes

2023-02-28 13:13 UTC, csukuangfj commented on sherpa-ncnn/csrc/hypothesis.h
> +  std::vector<float> timestamps;
Is there a reason to use float here?

2023-02-28 13:13 UTC, csukuangfj commented on sherpa-ncnn/csrc/recognizer.cc
> +  return std::move(r);
```suggestion
  return r;
```

2023-02-28 13:13 UTC, csukuangfj commented on sherpa-ncnn/csrc/recognizer.h
> +  std::unique_ptr<knf::FbankOptions> fbank_opts_;
```suggestion
  knf::FbankOptions fbank_opts_;
```

2023-02-28 13:13 UTC, csukuangfj commented on sherpa-ncnn/csrc/recognizer.cc
> +    t *= frame_shift_s;
```suggestion
    t *= frame_shift_s * 4;
```

You can assume that the subsampling factor is 4.

2023-02-28 13:18 UTC, csukuangfj commented
Could you use
https://github.com/k2-fsa/sherpa-ncnn/blob/master/scripts/check_style_cpplint.sh
to fix your code style?

2023-02-28 13:19 UTC, csukuangfj commented
> [sherpa-ncnn-alsa.cc](https://github.com/k2-fsa/sherpa-ncnn/blob/master/sherpa-ncnn/csrc/sherpa-ncnn-alsa.cc) and [sherpa-ncnn-microphone.cc](https://github.com/k2-fsa/sherpa-ncnn/blob/master/sherpa-ncnn/csrc/sherpa-ncnn-microphone.cc) need to print timestamps result

Could you support these two files as well?

2023-03-01 03:03 UTC, xiangxyq commented
> Could you use https://github.com/k2-fsa/sherpa-ncnn/blob/master/scripts/check_style_cpplint.sh to fix your code style?

ok

2023-03-01 03:24 UTC, xiangxyq commented
> Thanks for your contribution!
> 
> > , here why push blanck_id to token, how to handle timestamps? this question also in
> 
> The reason is to make the following code easier to write
> 
> https://github.com/k2-fsa/sherpa-ncnn/blob/b80b74695be0eafcc7a3815a5647899b7b9a82b5/sherpa-ncnn/csrc/greedy-search-decoder.cc#L31-L36
> 
> If we put blanks at the beginning, we don't need to test whether the vector `result_.tokens` is empty or not

i see, will lead tokens size() != timestamps size(),  remove blank token in Recognizer::GetResult()?

https://github.com/xiangxyq/sherpa-ncnn/blob/0f30fb825f1a81018168014f036ec4f8a15cb786/sherpa-ncnn/csrc/recognizer.cc#L89-L98

2023-03-01 04:47 UTC, csukuangfj commented
@xiangxyq 
Thanks again for your contribution. I am merging it and am also refactoring the code.

2023-03-01 04:47 UTC, merged

2023-03-01 07:01 UTC, xiangxyq commented
@csukuangfj some suggest has not to do, will continue to do.

2023-03-01 07:02 UTC, csukuangfj commented
> @csukuangfj some suggest has not to do, need continue.

Please wait before I finish refactoring the code.

Thanks!